project:
  type: website
  output-dir: docs

website:
  title: "saqr"
  description: "Personal website of Mohammed Saqr"
  site-url: https://loxavia.github.io
  repo-url: https://github.com/loxavia/loxavia.github.io
  google-analytics: "G-J5QY9QMC46"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@mohsaqr"
    site: "@mohsaqr"
    card-style: "summary_large_image"
  navbar:
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: interests.qmd
      - href: cv.qmd
      - href: publications.qmd
      # - href: blog.qmd
  page-footer:
    right: 
      - text: "<span style='text-sm'>Based on <a target='_blank' href='https://github.com/ddimmery/quarto-website'>ddimmery</a></span>"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
resources:
  - CNAME
