---
title: "Untitled"
format: docx

---
 
```{r, include=F,message=F, warning=F}

library(dplyr)
source("apa.R")
Publications = rio::import("cv.xlsx", sheet = "Publications") %>% arrange(desc(Year))

(Publications) %>% ungroup %>% dplyr::mutate(seq = seq_along(Title)) -> Publications
Publications %>%  rowwise %>% 
  dplyr::mutate(Ref = generateAPARef(Publications[seq,],F)) -> Publications
```

 
```{r, echo= F, message = T, warning=F, results = 'asis'}
pub_types = unique(Publications$`Document Type`)
pub_tags <- htmltools::tagList()
  year_tags = htmltools::tagList()
  ds <- Publications 
  years <- unique(ds$Year)
  for (y in 1:length(years)){
    research_tags = htmltools::tagList()

    dy <- ds %>% filter(Year == years[y])
    for (i in 1:nrow(dy)) {
      if (!is.na(dy[i,]$Ref)){
        research_tags[[i]] <- htmltools::HTML(dy[i,]$Ref)
      }
    }
    titletag <- htmltools::tags$h3(paste0(years[y]))
    
    year_tags[[y]] <- htmltools::tagList(
      titletag,
      htmltools::tags$ul(
        research_tags,
        style="padding-left: 3rem"
      )
    )
  }
  
  year_tags

```

```{r, echo= F, message = F, warning=F}
pub_types = unique(Publications$`Document Type`)
pub_tags <- htmltools::tagList()
for (p in 1:length(pub_types)) {
  year_tags = htmltools::tagList()
  ds <- Publications %>% filter(`Document Type` == pub_types[p]) 
  dsy <- ds %>% filter(Year >= 2017)
  years <- unique(dsy$Year)
  if (nrow(ds) != nrow(dsy)) {
    years <- c(years, "Before 2017")
  }
  for (y in 1:length(years)){
    research_tags = htmltools::tagList()
    
    dy <- ds %>% filter(Year == years[y])
    if (years[y] == "Before 2017") {
      dy <- ds %>% filter(Year <= 2017)
    }
    for (i in 1:nrow(dy)) {
      if (!is.na(dy[i,]$Ref)){
        research_tags[[i]] <- htmltools::HTML(dy[i,]$Ref)
      }
    }
    titletag <- htmltools::tags$h3(paste0(years[y]))
    if(pub_types[p]%in%c("Editorial","Other publication","Thesis")) {
      titletag<-htmltools::tags$span("")
    }
    year_tags[[y]] <- htmltools::tagList(
      titletag,
      htmltools::tags$ul(
        research_tags,
        style="padding-left: 3rem"
      )
    )
  }
  pub_tags[[p]] <- htmltools::tagList(
      htmltools::tags$h2(ifelse(pub_types[p] == "Thesis", "Thesis",paste0(pub_types[p],"s"))),
        year_tags
    )
}
(pub_tags)
```
 

